<?php
/**
 * This file is part of the Lackky API.
 *
 * (c) Lackky Team <hello@lackky.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */
namespace Lackky\Models;
use Phalcon\Filter;

/**
 * Posts
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2020-02-20, 03:12:55
 */
class Posts extends ModelBase
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $userId;

    /**
     *
     * @var string
     */
    protected $title;

    /**
     *
     * @var string
     */
    protected $description;

    /**
     *
     * @var string
     */
    protected $image;

    /**
     *
     * @var string
     */
    protected $video;

    /**
     *
     * @var string
     */
    protected $hashTag;

    /**
     *
     * @var integer
     */
    protected $numberView;

    /**
     *
     * @var integer
     */
    protected $numberReply;

    /**
     *
     * @var string
     */
    protected $status;

    /**
     *
     * @var integer
     */
    protected $createdAt;

    /**
     *
     * @var integer
     */
    protected $updatedAt;

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field userId
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Returns the value of field title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Returns the value of field description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Returns the value of field image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Returns the value of field video
     *
     * @return string
     */
    public function getVideo()
    {
        return $this->video;
    }

    /**
     * Returns the value of field hashTag
     *
     * @return string
     */
    public function getHashTag()
    {
        return $this->hashTag;
    }

    /**
     * Returns the value of field numberView
     *
     * @return integer
     */
    public function getNumberView()
    {
        return $this->numberView;
    }

    /**
     * Returns the value of field numberReply
     *
     * @return integer
     */
    public function getNumberReply()
    {
        return $this->numberReply;
    }

    /**
     * Returns the value of field status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Returns the value of field createdAt
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Returns the value of field updatedAt
     *
     * @return integer
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSource("posts");
        $this->belongsTo(
            'userId',
            Users::class,
            'id',
            ['alias' => 'user']
        );
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'user_id' => 'userId',
            'title' => 'title',
            'description' => 'description',
            'image' => 'image',
            'video' => 'video',
            'hash_tag' => 'hashTag',
            'number_view' => 'numberView',
            'number_reply' => 'numberReply',
            'status' => 'status',
            'created_at' => 'createdAt',
            'updated_at' => 'updatedAt'
        ];
    }

    /**
     * Returns an array of the fields/filters for this model
     *
     * @return array<string,string>
     */
    public function getModelFilters(): array
    {
        return [
            'id' => Filter::FILTER_INT,
            'title' => Filter::FILTER_STRING,
            'description' => Filter::FILTER_STRING,
            'image' => Filter::FILTER_STRING,
            'video' => Filter::FILTER_STRING,
            'hashTag' => Filter::FILTER_STRING,
            'numberView' => Filter::FILTER_INT,
            'numberReply' => Filter::FILTER_INT,
            'status' => Filter::FILTER_INT,
            'createdAt' => Filter::FILTER_INT,
            'updatedAt' => Filter::FILTER_INT
        ];
    }
}
